// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package grpc

import (
	"net"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockServer creates a new instance of MockServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServer {
	mock := &MockServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServer is an autogenerated mock type for the Server type
type MockServer struct {
	mock.Mock
}

type MockServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServer) EXPECT() *MockServer_Expecter {
	return &MockServer_Expecter{mock: &_m.Mock}
}

// GracefulStop provides a mock function for the type MockServer
func (_mock *MockServer) GracefulStop() {
	_mock.Called()
	return
}

// MockServer_GracefulStop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GracefulStop'
type MockServer_GracefulStop_Call struct {
	*mock.Call
}

// GracefulStop is a helper method to define mock.On call
func (_e *MockServer_Expecter) GracefulStop() *MockServer_GracefulStop_Call {
	return &MockServer_GracefulStop_Call{Call: _e.mock.On("GracefulStop")}
}

func (_c *MockServer_GracefulStop_Call) Run(run func()) *MockServer_GracefulStop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServer_GracefulStop_Call) Return() *MockServer_GracefulStop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServer_GracefulStop_Call) RunAndReturn(run func()) *MockServer_GracefulStop_Call {
	_c.Run(run)
	return _c
}

// Inject provides a mock function for the type MockServer
func (_mock *MockServer) Inject() grpc.ServiceRegistrar {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Inject")
	}

	var r0 grpc.ServiceRegistrar
	if returnFunc, ok := ret.Get(0).(func() grpc.ServiceRegistrar); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ServiceRegistrar)
		}
	}
	return r0
}

// MockServer_Inject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Inject'
type MockServer_Inject_Call struct {
	*mock.Call
}

// Inject is a helper method to define mock.On call
func (_e *MockServer_Expecter) Inject() *MockServer_Inject_Call {
	return &MockServer_Inject_Call{Call: _e.mock.On("Inject")}
}

func (_c *MockServer_Inject_Call) Run(run func()) *MockServer_Inject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServer_Inject_Call) Return(serviceRegistrar grpc.ServiceRegistrar) *MockServer_Inject_Call {
	_c.Call.Return(serviceRegistrar)
	return _c
}

func (_c *MockServer_Inject_Call) RunAndReturn(run func() grpc.ServiceRegistrar) *MockServer_Inject_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterRoutes provides a mock function for the type MockServer
func (_mock *MockServer) RegisterRoutes(fns ...func(Server)) {
	if len(fns) > 0 {
		_mock.Called(fns)
	} else {
		_mock.Called()
	}

	return
}

// MockServer_RegisterRoutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterRoutes'
type MockServer_RegisterRoutes_Call struct {
	*mock.Call
}

// RegisterRoutes is a helper method to define mock.On call
//   - fns ...func(Server)
func (_e *MockServer_Expecter) RegisterRoutes(fns ...interface{}) *MockServer_RegisterRoutes_Call {
	return &MockServer_RegisterRoutes_Call{Call: _e.mock.On("RegisterRoutes",
		append([]interface{}{}, fns...)...)}
}

func (_c *MockServer_RegisterRoutes_Call) Run(run func(fns ...func(Server))) *MockServer_RegisterRoutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []func(Server)
		var variadicArgs []func(Server)
		if len(args) > 0 {
			variadicArgs = args[0].([]func(Server))
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockServer_RegisterRoutes_Call) Return() *MockServer_RegisterRoutes_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServer_RegisterRoutes_Call) RunAndReturn(run func(fns ...func(Server))) *MockServer_RegisterRoutes_Call {
	_c.Run(run)
	return _c
}

// Routes provides a mock function for the type MockServer
func (_mock *MockServer) Routes() {
	_mock.Called()
	return
}

// MockServer_Routes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Routes'
type MockServer_Routes_Call struct {
	*mock.Call
}

// Routes is a helper method to define mock.On call
func (_e *MockServer_Expecter) Routes() *MockServer_Routes_Call {
	return &MockServer_Routes_Call{Call: _e.mock.On("Routes")}
}

func (_c *MockServer_Routes_Call) Run(run func()) *MockServer_Routes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServer_Routes_Call) Return() *MockServer_Routes_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServer_Routes_Call) RunAndReturn(run func()) *MockServer_Routes_Call {
	_c.Run(run)
	return _c
}

// Serve provides a mock function for the type MockServer
func (_mock *MockServer) Serve(listener net.Listener) {
	_mock.Called(listener)
	return
}

// MockServer_Serve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serve'
type MockServer_Serve_Call struct {
	*mock.Call
}

// Serve is a helper method to define mock.On call
//   - listener net.Listener
func (_e *MockServer_Expecter) Serve(listener interface{}) *MockServer_Serve_Call {
	return &MockServer_Serve_Call{Call: _e.mock.On("Serve", listener)}
}

func (_c *MockServer_Serve_Call) Run(run func(listener net.Listener)) *MockServer_Serve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 net.Listener
		if args[0] != nil {
			arg0 = args[0].(net.Listener)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServer_Serve_Call) Return() *MockServer_Serve_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServer_Serve_Call) RunAndReturn(run func(listener net.Listener)) *MockServer_Serve_Call {
	_c.Run(run)
	return _c
}
