package oauth

const (
	ENV_AUTH_PRIVATE_KEY                     = "AUTH_PRIVATE_KEY"
	ENV_AUTH_PUBLIC_KEY                      = "AUTH_PUBLIC_KEY"
	ENV_AUTH_JWT_EXPIRATION_DURATION         = "AUTH_JWT_EXPIRATION_DURATION"
	ENV_AUTH_JWT_REFRESH_EXPIRATION_DURATION = "AUTH_JWT_REFRESH_EXPIRATION_DURATION"
)
