// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oauth

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockToken creates a new instance of MockToken. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToken(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToken {
	mock := &MockToken{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToken is an autogenerated mock type for the Token type
type MockToken struct {
	mock.Mock
}

type MockToken_Expecter struct {
	mock *mock.Mock
}

func (_m *MockToken) EXPECT() *MockToken_Expecter {
	return &MockToken_Expecter{mock: &_m.Mock}
}

// BearerToken provides a mock function for the type MockToken
func (_mock *MockToken) BearerToken() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BearerToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToken_BearerToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BearerToken'
type MockToken_BearerToken_Call struct {
	*mock.Call
}

// BearerToken is a helper method to define mock.On call
func (_e *MockToken_Expecter) BearerToken() *MockToken_BearerToken_Call {
	return &MockToken_BearerToken_Call{Call: _e.mock.On("BearerToken")}
}

func (_c *MockToken_BearerToken_Call) Run(run func()) *MockToken_BearerToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockToken_BearerToken_Call) Return(s string, err error) *MockToken_BearerToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockToken_BearerToken_Call) RunAndReturn(run func() (string, error)) *MockToken_BearerToken_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type MockToken
func (_mock *MockToken) RefreshToken() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToken_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockToken_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
func (_e *MockToken_Expecter) RefreshToken() *MockToken_RefreshToken_Call {
	return &MockToken_RefreshToken_Call{Call: _e.mock.On("RefreshToken")}
}

func (_c *MockToken_RefreshToken_Call) Run(run func()) *MockToken_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockToken_RefreshToken_Call) Return(s string, err error) *MockToken_RefreshToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockToken_RefreshToken_Call) RunAndReturn(run func() (string, error)) *MockToken_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
