// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oauth

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockClaims creates a new instance of MockClaims. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClaims(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClaims {
	mock := &MockClaims{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClaims is an autogenerated mock type for the Claims type
type MockClaims struct {
	mock.Mock
}

type MockClaims_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClaims) EXPECT() *MockClaims_Expecter {
	return &MockClaims_Expecter{mock: &_m.Mock}
}

// Base64Encode provides a mock function for the type MockClaims
func (_mock *MockClaims) Base64Encode() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Base64Encode")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClaims_Base64Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Base64Encode'
type MockClaims_Base64Encode_Call struct {
	*mock.Call
}

// Base64Encode is a helper method to define mock.On call
func (_e *MockClaims_Expecter) Base64Encode() *MockClaims_Base64Encode_Call {
	return &MockClaims_Base64Encode_Call{Call: _e.mock.On("Base64Encode")}
}

func (_c *MockClaims_Base64Encode_Call) Run(run func()) *MockClaims_Base64Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_Base64Encode_Call) Return(s string, err error) *MockClaims_Base64Encode_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClaims_Base64Encode_Call) RunAndReturn(run func() (string, error)) *MockClaims_Base64Encode_Call {
	_c.Call.Return(run)
	return _c
}

// GetAudience provides a mock function for the type MockClaims
func (_mock *MockClaims) GetAudience() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAudience")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClaims_GetAudience_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAudience'
type MockClaims_GetAudience_Call struct {
	*mock.Call
}

// GetAudience is a helper method to define mock.On call
func (_e *MockClaims_Expecter) GetAudience() *MockClaims_GetAudience_Call {
	return &MockClaims_GetAudience_Call{Call: _e.mock.On("GetAudience")}
}

func (_c *MockClaims_GetAudience_Call) Run(run func()) *MockClaims_GetAudience_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_GetAudience_Call) Return(s string) *MockClaims_GetAudience_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClaims_GetAudience_Call) RunAndReturn(run func() string) *MockClaims_GetAudience_Call {
	_c.Call.Return(run)
	return _c
}

// GetClientID provides a mock function for the type MockClaims
func (_mock *MockClaims) GetClientID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClientID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClaims_GetClientID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientID'
type MockClaims_GetClientID_Call struct {
	*mock.Call
}

// GetClientID is a helper method to define mock.On call
func (_e *MockClaims_Expecter) GetClientID() *MockClaims_GetClientID_Call {
	return &MockClaims_GetClientID_Call{Call: _e.mock.On("GetClientID")}
}

func (_c *MockClaims_GetClientID_Call) Run(run func()) *MockClaims_GetClientID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_GetClientID_Call) Return(s string) *MockClaims_GetClientID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClaims_GetClientID_Call) RunAndReturn(run func() string) *MockClaims_GetClientID_Call {
	_c.Call.Return(run)
	return _c
}

// GetIssuer provides a mock function for the type MockClaims
func (_mock *MockClaims) GetIssuer() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetIssuer")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClaims_GetIssuer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIssuer'
type MockClaims_GetIssuer_Call struct {
	*mock.Call
}

// GetIssuer is a helper method to define mock.On call
func (_e *MockClaims_Expecter) GetIssuer() *MockClaims_GetIssuer_Call {
	return &MockClaims_GetIssuer_Call{Call: _e.mock.On("GetIssuer")}
}

func (_c *MockClaims_GetIssuer_Call) Run(run func()) *MockClaims_GetIssuer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_GetIssuer_Call) Return(s string) *MockClaims_GetIssuer_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClaims_GetIssuer_Call) RunAndReturn(run func() string) *MockClaims_GetIssuer_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetadata provides a mock function for the type MockClaims
func (_mock *MockClaims) GetMetadata() map[string]interface{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMetadata")
	}

	var r0 map[string]interface{}
	if returnFunc, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}
	return r0
}

// MockClaims_GetMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetadata'
type MockClaims_GetMetadata_Call struct {
	*mock.Call
}

// GetMetadata is a helper method to define mock.On call
func (_e *MockClaims_Expecter) GetMetadata() *MockClaims_GetMetadata_Call {
	return &MockClaims_GetMetadata_Call{Call: _e.mock.On("GetMetadata")}
}

func (_c *MockClaims_GetMetadata_Call) Run(run func()) *MockClaims_GetMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_GetMetadata_Call) Return(stringToIfaceVal map[string]interface{}) *MockClaims_GetMetadata_Call {
	_c.Call.Return(stringToIfaceVal)
	return _c
}

func (_c *MockClaims_GetMetadata_Call) RunAndReturn(run func() map[string]interface{}) *MockClaims_GetMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissions provides a mock function for the type MockClaims
func (_mock *MockClaims) GetPermissions() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPermissions")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockClaims_GetPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissions'
type MockClaims_GetPermissions_Call struct {
	*mock.Call
}

// GetPermissions is a helper method to define mock.On call
func (_e *MockClaims_Expecter) GetPermissions() *MockClaims_GetPermissions_Call {
	return &MockClaims_GetPermissions_Call{Call: _e.mock.On("GetPermissions")}
}

func (_c *MockClaims_GetPermissions_Call) Run(run func()) *MockClaims_GetPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_GetPermissions_Call) Return(strings []string) *MockClaims_GetPermissions_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockClaims_GetPermissions_Call) RunAndReturn(run func() []string) *MockClaims_GetPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoles provides a mock function for the type MockClaims
func (_mock *MockClaims) GetRoles() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRoles")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockClaims_GetRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoles'
type MockClaims_GetRoles_Call struct {
	*mock.Call
}

// GetRoles is a helper method to define mock.On call
func (_e *MockClaims_Expecter) GetRoles() *MockClaims_GetRoles_Call {
	return &MockClaims_GetRoles_Call{Call: _e.mock.On("GetRoles")}
}

func (_c *MockClaims_GetRoles_Call) Run(run func()) *MockClaims_GetRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_GetRoles_Call) Return(strings []string) *MockClaims_GetRoles_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockClaims_GetRoles_Call) RunAndReturn(run func() []string) *MockClaims_GetRoles_Call {
	_c.Call.Return(run)
	return _c
}

// GetSub provides a mock function for the type MockClaims
func (_mock *MockClaims) GetSub() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSub")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClaims_GetSub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSub'
type MockClaims_GetSub_Call struct {
	*mock.Call
}

// GetSub is a helper method to define mock.On call
func (_e *MockClaims_Expecter) GetSub() *MockClaims_GetSub_Call {
	return &MockClaims_GetSub_Call{Call: _e.mock.On("GetSub")}
}

func (_c *MockClaims_GetSub_Call) Run(run func()) *MockClaims_GetSub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_GetSub_Call) Return(s string) *MockClaims_GetSub_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClaims_GetSub_Call) RunAndReturn(run func() string) *MockClaims_GetSub_Call {
	_c.Call.Return(run)
	return _c
}

// IsExpired provides a mock function for the type MockClaims
func (_mock *MockClaims) IsExpired() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsExpired")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockClaims_IsExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsExpired'
type MockClaims_IsExpired_Call struct {
	*mock.Call
}

// IsExpired is a helper method to define mock.On call
func (_e *MockClaims_Expecter) IsExpired() *MockClaims_IsExpired_Call {
	return &MockClaims_IsExpired_Call{Call: _e.mock.On("IsExpired")}
}

func (_c *MockClaims_IsExpired_Call) Run(run func()) *MockClaims_IsExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_IsExpired_Call) Return(b bool) *MockClaims_IsExpired_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockClaims_IsExpired_Call) RunAndReturn(run func() bool) *MockClaims_IsExpired_Call {
	_c.Call.Return(run)
	return _c
}

// setBearerExp provides a mock function for the type MockClaims
func (_mock *MockClaims) setBearerExp() {
	_mock.Called()
	return
}

// MockClaims_setBearerExp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setBearerExp'
type MockClaims_setBearerExp_Call struct {
	*mock.Call
}

// setBearerExp is a helper method to define mock.On call
func (_e *MockClaims_Expecter) setBearerExp() *MockClaims_setBearerExp_Call {
	return &MockClaims_setBearerExp_Call{Call: _e.mock.On("setBearerExp")}
}

func (_c *MockClaims_setBearerExp_Call) Run(run func()) *MockClaims_setBearerExp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_setBearerExp_Call) Return() *MockClaims_setBearerExp_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClaims_setBearerExp_Call) RunAndReturn(run func()) *MockClaims_setBearerExp_Call {
	_c.Run(run)
	return _c
}

// setRefreshExp provides a mock function for the type MockClaims
func (_mock *MockClaims) setRefreshExp() {
	_mock.Called()
	return
}

// MockClaims_setRefreshExp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setRefreshExp'
type MockClaims_setRefreshExp_Call struct {
	*mock.Call
}

// setRefreshExp is a helper method to define mock.On call
func (_e *MockClaims_Expecter) setRefreshExp() *MockClaims_setRefreshExp_Call {
	return &MockClaims_setRefreshExp_Call{Call: _e.mock.On("setRefreshExp")}
}

func (_c *MockClaims_setRefreshExp_Call) Run(run func()) *MockClaims_setRefreshExp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_setRefreshExp_Call) Return() *MockClaims_setRefreshExp_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClaims_setRefreshExp_Call) RunAndReturn(run func()) *MockClaims_setRefreshExp_Call {
	_c.Run(run)
	return _c
}
