// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oauth

import (
	"context"

	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockResourceServer creates a new instance of MockResourceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResourceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResourceServer {
	mock := &MockResourceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResourceServer is an autogenerated mock type for the ResourceServer type
type MockResourceServer struct {
	mock.Mock
}

type MockResourceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResourceServer) EXPECT() *MockResourceServer_Expecter {
	return &MockResourceServer_Expecter{mock: &_m.Mock}
}

// BearerTokenMiddleware provides a mock function for the type MockResourceServer
func (_mock *MockResourceServer) BearerTokenMiddleware() func(*gin.Context) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BearerTokenMiddleware")
	}

	var r0 func(*gin.Context)
	if returnFunc, ok := ret.Get(0).(func() func(*gin.Context)); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(*gin.Context))
		}
	}
	return r0
}

// MockResourceServer_BearerTokenMiddleware_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BearerTokenMiddleware'
type MockResourceServer_BearerTokenMiddleware_Call struct {
	*mock.Call
}

// BearerTokenMiddleware is a helper method to define mock.On call
func (_e *MockResourceServer_Expecter) BearerTokenMiddleware() *MockResourceServer_BearerTokenMiddleware_Call {
	return &MockResourceServer_BearerTokenMiddleware_Call{Call: _e.mock.On("BearerTokenMiddleware")}
}

func (_c *MockResourceServer_BearerTokenMiddleware_Call) Run(run func()) *MockResourceServer_BearerTokenMiddleware_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResourceServer_BearerTokenMiddleware_Call) Return(fn func(*gin.Context)) *MockResourceServer_BearerTokenMiddleware_Call {
	_c.Call.Return(fn)
	return _c
}

func (_c *MockResourceServer_BearerTokenMiddleware_Call) RunAndReturn(run func() func(*gin.Context)) *MockResourceServer_BearerTokenMiddleware_Call {
	_c.Call.Return(run)
	return _c
}

// GRPCBearerTokenMiddleware provides a mock function for the type MockResourceServer
func (_mock *MockResourceServer) GRPCBearerTokenMiddleware(s string) func(ctx context.Context, req any, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (resp any, err error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GRPCBearerTokenMiddleware")
	}

	var r0 func(ctx context.Context, req any, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (resp any, err error)
	if returnFunc, ok := ret.Get(0).(func(string) func(ctx context.Context, req any, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (resp any, err error)); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(ctx context.Context, req any, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (resp any, err error))
		}
	}
	return r0
}

// MockResourceServer_GRPCBearerTokenMiddleware_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GRPCBearerTokenMiddleware'
type MockResourceServer_GRPCBearerTokenMiddleware_Call struct {
	*mock.Call
}

// GRPCBearerTokenMiddleware is a helper method to define mock.On call
//   - s string
func (_e *MockResourceServer_Expecter) GRPCBearerTokenMiddleware(s interface{}) *MockResourceServer_GRPCBearerTokenMiddleware_Call {
	return &MockResourceServer_GRPCBearerTokenMiddleware_Call{Call: _e.mock.On("GRPCBearerTokenMiddleware", s)}
}

func (_c *MockResourceServer_GRPCBearerTokenMiddleware_Call) Run(run func(s string)) *MockResourceServer_GRPCBearerTokenMiddleware_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResourceServer_GRPCBearerTokenMiddleware_Call) Return(fn func(ctx context.Context, req any, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (resp any, err error)) *MockResourceServer_GRPCBearerTokenMiddleware_Call {
	_c.Call.Return(fn)
	return _c
}

func (_c *MockResourceServer_GRPCBearerTokenMiddleware_Call) RunAndReturn(run func(s string) func(ctx context.Context, req any, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (resp any, err error)) *MockResourceServer_GRPCBearerTokenMiddleware_Call {
	_c.Call.Return(run)
	return _c
}

// GRPCIdentityClient provides a mock function for the type MockResourceServer
func (_mock *MockResourceServer) GRPCIdentityClient(ctx context.Context) AuthorizedClient {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GRPCIdentityClient")
	}

	var r0 AuthorizedClient
	if returnFunc, ok := ret.Get(0).(func(context.Context) AuthorizedClient); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(AuthorizedClient)
	}
	return r0
}

// MockResourceServer_GRPCIdentityClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GRPCIdentityClient'
type MockResourceServer_GRPCIdentityClient_Call struct {
	*mock.Call
}

// GRPCIdentityClient is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockResourceServer_Expecter) GRPCIdentityClient(ctx interface{}) *MockResourceServer_GRPCIdentityClient_Call {
	return &MockResourceServer_GRPCIdentityClient_Call{Call: _e.mock.On("GRPCIdentityClient", ctx)}
}

func (_c *MockResourceServer_GRPCIdentityClient_Call) Run(run func(ctx context.Context)) *MockResourceServer_GRPCIdentityClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResourceServer_GRPCIdentityClient_Call) Return(authorizedClient AuthorizedClient) *MockResourceServer_GRPCIdentityClient_Call {
	_c.Call.Return(authorizedClient)
	return _c
}

func (_c *MockResourceServer_GRPCIdentityClient_Call) RunAndReturn(run func(ctx context.Context) AuthorizedClient) *MockResourceServer_GRPCIdentityClient_Call {
	_c.Call.Return(run)
	return _c
}

// GRPCIdentityUser provides a mock function for the type MockResourceServer
func (_mock *MockResourceServer) GRPCIdentityUser(ctx context.Context) IdentityUser {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GRPCIdentityUser")
	}

	var r0 IdentityUser
	if returnFunc, ok := ret.Get(0).(func(context.Context) IdentityUser); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(IdentityUser)
	}
	return r0
}

// MockResourceServer_GRPCIdentityUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GRPCIdentityUser'
type MockResourceServer_GRPCIdentityUser_Call struct {
	*mock.Call
}

// GRPCIdentityUser is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockResourceServer_Expecter) GRPCIdentityUser(ctx interface{}) *MockResourceServer_GRPCIdentityUser_Call {
	return &MockResourceServer_GRPCIdentityUser_Call{Call: _e.mock.On("GRPCIdentityUser", ctx)}
}

func (_c *MockResourceServer_GRPCIdentityUser_Call) Run(run func(ctx context.Context)) *MockResourceServer_GRPCIdentityUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResourceServer_GRPCIdentityUser_Call) Return(identityUser IdentityUser) *MockResourceServer_GRPCIdentityUser_Call {
	_c.Call.Return(identityUser)
	return _c
}

func (_c *MockResourceServer_GRPCIdentityUser_Call) RunAndReturn(run func(ctx context.Context) IdentityUser) *MockResourceServer_GRPCIdentityUser_Call {
	_c.Call.Return(run)
	return _c
}

// GinIdentityClient provides a mock function for the type MockResourceServer
func (_mock *MockResourceServer) GinIdentityClient(c *gin.Context) AuthorizedClient {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GinIdentityClient")
	}

	var r0 AuthorizedClient
	if returnFunc, ok := ret.Get(0).(func(*gin.Context) AuthorizedClient); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Get(0).(AuthorizedClient)
	}
	return r0
}

// MockResourceServer_GinIdentityClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GinIdentityClient'
type MockResourceServer_GinIdentityClient_Call struct {
	*mock.Call
}

// GinIdentityClient is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockResourceServer_Expecter) GinIdentityClient(c interface{}) *MockResourceServer_GinIdentityClient_Call {
	return &MockResourceServer_GinIdentityClient_Call{Call: _e.mock.On("GinIdentityClient", c)}
}

func (_c *MockResourceServer_GinIdentityClient_Call) Run(run func(c *gin.Context)) *MockResourceServer_GinIdentityClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResourceServer_GinIdentityClient_Call) Return(authorizedClient AuthorizedClient) *MockResourceServer_GinIdentityClient_Call {
	_c.Call.Return(authorizedClient)
	return _c
}

func (_c *MockResourceServer_GinIdentityClient_Call) RunAndReturn(run func(c *gin.Context) AuthorizedClient) *MockResourceServer_GinIdentityClient_Call {
	_c.Call.Return(run)
	return _c
}

// GinIdentityUser provides a mock function for the type MockResourceServer
func (_mock *MockResourceServer) GinIdentityUser(c *gin.Context) IdentityUser {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GinIdentityUser")
	}

	var r0 IdentityUser
	if returnFunc, ok := ret.Get(0).(func(*gin.Context) IdentityUser); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Get(0).(IdentityUser)
	}
	return r0
}

// MockResourceServer_GinIdentityUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GinIdentityUser'
type MockResourceServer_GinIdentityUser_Call struct {
	*mock.Call
}

// GinIdentityUser is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockResourceServer_Expecter) GinIdentityUser(c interface{}) *MockResourceServer_GinIdentityUser_Call {
	return &MockResourceServer_GinIdentityUser_Call{Call: _e.mock.On("GinIdentityUser", c)}
}

func (_c *MockResourceServer_GinIdentityUser_Call) Run(run func(c *gin.Context)) *MockResourceServer_GinIdentityUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResourceServer_GinIdentityUser_Call) Return(identityUser IdentityUser) *MockResourceServer_GinIdentityUser_Call {
	_c.Call.Return(identityUser)
	return _c
}

func (_c *MockResourceServer_GinIdentityUser_Call) RunAndReturn(run func(c *gin.Context) IdentityUser) *MockResourceServer_GinIdentityUser_Call {
	_c.Call.Return(run)
	return _c
}
