// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oauth

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockHeader creates a new instance of MockHeader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHeader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHeader {
	mock := &MockHeader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHeader is an autogenerated mock type for the Header type
type MockHeader struct {
	mock.Mock
}

type MockHeader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHeader) EXPECT() *MockHeader_Expecter {
	return &MockHeader_Expecter{mock: &_m.Mock}
}

// Base64Encode provides a mock function for the type MockHeader
func (_mock *MockHeader) Base64Encode() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Base64Encode")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHeader_Base64Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Base64Encode'
type MockHeader_Base64Encode_Call struct {
	*mock.Call
}

// Base64Encode is a helper method to define mock.On call
func (_e *MockHeader_Expecter) Base64Encode() *MockHeader_Base64Encode_Call {
	return &MockHeader_Base64Encode_Call{Call: _e.mock.On("Base64Encode")}
}

func (_c *MockHeader_Base64Encode_Call) Run(run func()) *MockHeader_Base64Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHeader_Base64Encode_Call) Return(s string, err error) *MockHeader_Base64Encode_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockHeader_Base64Encode_Call) RunAndReturn(run func() (string, error)) *MockHeader_Base64Encode_Call {
	_c.Call.Return(run)
	return _c
}
