// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oauth

import (
	"context"

	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthorizationServer creates a new instance of MockAuthorizationServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorizationServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorizationServer {
	mock := &MockAuthorizationServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthorizationServer is an autogenerated mock type for the AuthorizationServer type
type MockAuthorizationServer struct {
	mock.Mock
}

type MockAuthorizationServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorizationServer) EXPECT() *MockAuthorizationServer_Expecter {
	return &MockAuthorizationServer_Expecter{mock: &_m.Mock}
}

// AuthorizedClientMiddleware provides a mock function for the type MockAuthorizationServer
func (_mock *MockAuthorizationServer) AuthorizedClientMiddleware() func(*gin.Context) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthorizedClientMiddleware")
	}

	var r0 func(*gin.Context)
	if returnFunc, ok := ret.Get(0).(func() func(*gin.Context)); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(*gin.Context))
		}
	}
	return r0
}

// MockAuthorizationServer_AuthorizedClientMiddleware_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthorizedClientMiddleware'
type MockAuthorizationServer_AuthorizedClientMiddleware_Call struct {
	*mock.Call
}

// AuthorizedClientMiddleware is a helper method to define mock.On call
func (_e *MockAuthorizationServer_Expecter) AuthorizedClientMiddleware() *MockAuthorizationServer_AuthorizedClientMiddleware_Call {
	return &MockAuthorizationServer_AuthorizedClientMiddleware_Call{Call: _e.mock.On("AuthorizedClientMiddleware")}
}

func (_c *MockAuthorizationServer_AuthorizedClientMiddleware_Call) Run(run func()) *MockAuthorizationServer_AuthorizedClientMiddleware_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthorizationServer_AuthorizedClientMiddleware_Call) Return(fn func(*gin.Context)) *MockAuthorizationServer_AuthorizedClientMiddleware_Call {
	_c.Call.Return(fn)
	return _c
}

func (_c *MockAuthorizationServer_AuthorizedClientMiddleware_Call) RunAndReturn(run func() func(*gin.Context)) *MockAuthorizationServer_AuthorizedClientMiddleware_Call {
	_c.Call.Return(run)
	return _c
}

// BearerTokenMiddleware provides a mock function for the type MockAuthorizationServer
func (_mock *MockAuthorizationServer) BearerTokenMiddleware() func(*gin.Context) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BearerTokenMiddleware")
	}

	var r0 func(*gin.Context)
	if returnFunc, ok := ret.Get(0).(func() func(*gin.Context)); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(*gin.Context))
		}
	}
	return r0
}

// MockAuthorizationServer_BearerTokenMiddleware_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BearerTokenMiddleware'
type MockAuthorizationServer_BearerTokenMiddleware_Call struct {
	*mock.Call
}

// BearerTokenMiddleware is a helper method to define mock.On call
func (_e *MockAuthorizationServer_Expecter) BearerTokenMiddleware() *MockAuthorizationServer_BearerTokenMiddleware_Call {
	return &MockAuthorizationServer_BearerTokenMiddleware_Call{Call: _e.mock.On("BearerTokenMiddleware")}
}

func (_c *MockAuthorizationServer_BearerTokenMiddleware_Call) Run(run func()) *MockAuthorizationServer_BearerTokenMiddleware_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthorizationServer_BearerTokenMiddleware_Call) Return(fn func(*gin.Context)) *MockAuthorizationServer_BearerTokenMiddleware_Call {
	_c.Call.Return(fn)
	return _c
}

func (_c *MockAuthorizationServer_BearerTokenMiddleware_Call) RunAndReturn(run func() func(*gin.Context)) *MockAuthorizationServer_BearerTokenMiddleware_Call {
	_c.Call.Return(run)
	return _c
}

// GRPCIdentityClient provides a mock function for the type MockAuthorizationServer
func (_mock *MockAuthorizationServer) GRPCIdentityClient(ctx context.Context) AuthorizedClient {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GRPCIdentityClient")
	}

	var r0 AuthorizedClient
	if returnFunc, ok := ret.Get(0).(func(context.Context) AuthorizedClient); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(AuthorizedClient)
	}
	return r0
}

// MockAuthorizationServer_GRPCIdentityClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GRPCIdentityClient'
type MockAuthorizationServer_GRPCIdentityClient_Call struct {
	*mock.Call
}

// GRPCIdentityClient is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuthorizationServer_Expecter) GRPCIdentityClient(ctx interface{}) *MockAuthorizationServer_GRPCIdentityClient_Call {
	return &MockAuthorizationServer_GRPCIdentityClient_Call{Call: _e.mock.On("GRPCIdentityClient", ctx)}
}

func (_c *MockAuthorizationServer_GRPCIdentityClient_Call) Run(run func(ctx context.Context)) *MockAuthorizationServer_GRPCIdentityClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthorizationServer_GRPCIdentityClient_Call) Return(authorizedClient AuthorizedClient) *MockAuthorizationServer_GRPCIdentityClient_Call {
	_c.Call.Return(authorizedClient)
	return _c
}

func (_c *MockAuthorizationServer_GRPCIdentityClient_Call) RunAndReturn(run func(ctx context.Context) AuthorizedClient) *MockAuthorizationServer_GRPCIdentityClient_Call {
	_c.Call.Return(run)
	return _c
}

// GRPCIdentityUser provides a mock function for the type MockAuthorizationServer
func (_mock *MockAuthorizationServer) GRPCIdentityUser(ctx context.Context) IdentityUser {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GRPCIdentityUser")
	}

	var r0 IdentityUser
	if returnFunc, ok := ret.Get(0).(func(context.Context) IdentityUser); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(IdentityUser)
	}
	return r0
}

// MockAuthorizationServer_GRPCIdentityUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GRPCIdentityUser'
type MockAuthorizationServer_GRPCIdentityUser_Call struct {
	*mock.Call
}

// GRPCIdentityUser is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuthorizationServer_Expecter) GRPCIdentityUser(ctx interface{}) *MockAuthorizationServer_GRPCIdentityUser_Call {
	return &MockAuthorizationServer_GRPCIdentityUser_Call{Call: _e.mock.On("GRPCIdentityUser", ctx)}
}

func (_c *MockAuthorizationServer_GRPCIdentityUser_Call) Run(run func(ctx context.Context)) *MockAuthorizationServer_GRPCIdentityUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthorizationServer_GRPCIdentityUser_Call) Return(identityUser IdentityUser) *MockAuthorizationServer_GRPCIdentityUser_Call {
	_c.Call.Return(identityUser)
	return _c
}

func (_c *MockAuthorizationServer_GRPCIdentityUser_Call) RunAndReturn(run func(ctx context.Context) IdentityUser) *MockAuthorizationServer_GRPCIdentityUser_Call {
	_c.Call.Return(run)
	return _c
}

// GinIdentityClient provides a mock function for the type MockAuthorizationServer
func (_mock *MockAuthorizationServer) GinIdentityClient(c *gin.Context) AuthorizedClient {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GinIdentityClient")
	}

	var r0 AuthorizedClient
	if returnFunc, ok := ret.Get(0).(func(*gin.Context) AuthorizedClient); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Get(0).(AuthorizedClient)
	}
	return r0
}

// MockAuthorizationServer_GinIdentityClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GinIdentityClient'
type MockAuthorizationServer_GinIdentityClient_Call struct {
	*mock.Call
}

// GinIdentityClient is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockAuthorizationServer_Expecter) GinIdentityClient(c interface{}) *MockAuthorizationServer_GinIdentityClient_Call {
	return &MockAuthorizationServer_GinIdentityClient_Call{Call: _e.mock.On("GinIdentityClient", c)}
}

func (_c *MockAuthorizationServer_GinIdentityClient_Call) Run(run func(c *gin.Context)) *MockAuthorizationServer_GinIdentityClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthorizationServer_GinIdentityClient_Call) Return(authorizedClient AuthorizedClient) *MockAuthorizationServer_GinIdentityClient_Call {
	_c.Call.Return(authorizedClient)
	return _c
}

func (_c *MockAuthorizationServer_GinIdentityClient_Call) RunAndReturn(run func(c *gin.Context) AuthorizedClient) *MockAuthorizationServer_GinIdentityClient_Call {
	_c.Call.Return(run)
	return _c
}

// GinIdentityUser provides a mock function for the type MockAuthorizationServer
func (_mock *MockAuthorizationServer) GinIdentityUser(c *gin.Context) IdentityUser {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GinIdentityUser")
	}

	var r0 IdentityUser
	if returnFunc, ok := ret.Get(0).(func(*gin.Context) IdentityUser); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Get(0).(IdentityUser)
	}
	return r0
}

// MockAuthorizationServer_GinIdentityUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GinIdentityUser'
type MockAuthorizationServer_GinIdentityUser_Call struct {
	*mock.Call
}

// GinIdentityUser is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockAuthorizationServer_Expecter) GinIdentityUser(c interface{}) *MockAuthorizationServer_GinIdentityUser_Call {
	return &MockAuthorizationServer_GinIdentityUser_Call{Call: _e.mock.On("GinIdentityUser", c)}
}

func (_c *MockAuthorizationServer_GinIdentityUser_Call) Run(run func(c *gin.Context)) *MockAuthorizationServer_GinIdentityUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthorizationServer_GinIdentityUser_Call) Return(identityUser IdentityUser) *MockAuthorizationServer_GinIdentityUser_Call {
	_c.Call.Return(identityUser)
	return _c
}

func (_c *MockAuthorizationServer_GinIdentityUser_Call) RunAndReturn(run func(c *gin.Context) IdentityUser) *MockAuthorizationServer_GinIdentityUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewToken provides a mock function for the type MockAuthorizationServer
func (_mock *MockAuthorizationServer) NewToken(claims Claims) Token {
	ret := _mock.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for NewToken")
	}

	var r0 Token
	if returnFunc, ok := ret.Get(0).(func(Claims) Token); ok {
		r0 = returnFunc(claims)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Token)
		}
	}
	return r0
}

// MockAuthorizationServer_NewToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewToken'
type MockAuthorizationServer_NewToken_Call struct {
	*mock.Call
}

// NewToken is a helper method to define mock.On call
//   - claims Claims
func (_e *MockAuthorizationServer_Expecter) NewToken(claims interface{}) *MockAuthorizationServer_NewToken_Call {
	return &MockAuthorizationServer_NewToken_Call{Call: _e.mock.On("NewToken", claims)}
}

func (_c *MockAuthorizationServer_NewToken_Call) Run(run func(claims Claims)) *MockAuthorizationServer_NewToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Claims
		if args[0] != nil {
			arg0 = args[0].(Claims)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthorizationServer_NewToken_Call) Return(token Token) *MockAuthorizationServer_NewToken_Call {
	_c.Call.Return(token)
	return _c
}

func (_c *MockAuthorizationServer_NewToken_Call) RunAndReturn(run func(claims Claims) Token) *MockAuthorizationServer_NewToken_Call {
	_c.Call.Return(run)
	return _c
}
