// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package stderr

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockError creates a new instance of MockError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockError(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockError {
	mock := &MockError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockError is an autogenerated mock type for the Error type
type MockError struct {
	mock.Mock
}

type MockError_Expecter struct {
	mock *mock.Mock
}

func (_m *MockError) EXPECT() *MockError_Expecter {
	return &MockError_Expecter{mock: &_m.Mock}
}

// Code provides a mock function for the type MockError
func (_mock *MockError) Code() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Code")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockError_Code_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Code'
type MockError_Code_Call struct {
	*mock.Call
}

// Code is a helper method to define mock.On call
func (_e *MockError_Expecter) Code() *MockError_Code_Call {
	return &MockError_Code_Call{Call: _e.mock.On("Code")}
}

func (_c *MockError_Code_Call) Run(run func()) *MockError_Code_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockError_Code_Call) Return(s string) *MockError_Code_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockError_Code_Call) RunAndReturn(run func() string) *MockError_Code_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function for the type MockError
func (_mock *MockError) Err() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockError_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MockError_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *MockError_Expecter) Err() *MockError_Err_Call {
	return &MockError_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *MockError_Err_Call) Run(run func()) *MockError_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockError_Err_Call) Return(err error) *MockError_Err_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockError_Err_Call) RunAndReturn(run func() error) *MockError_Err_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function for the type MockError
func (_mock *MockError) Error() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockError_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockError_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *MockError_Expecter) Error() *MockError_Error_Call {
	return &MockError_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *MockError_Error_Call) Run(run func()) *MockError_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockError_Error_Call) Return(s string) *MockError_Error_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockError_Error_Call) RunAndReturn(run func() string) *MockError_Error_Call {
	_c.Call.Return(run)
	return _c
}

// HttpCode provides a mock function for the type MockError
func (_mock *MockError) HttpCode() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HttpCode")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockError_HttpCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HttpCode'
type MockError_HttpCode_Call struct {
	*mock.Call
}

// HttpCode is a helper method to define mock.On call
func (_e *MockError_Expecter) HttpCode() *MockError_HttpCode_Call {
	return &MockError_HttpCode_Call{Call: _e.mock.On("HttpCode")}
}

func (_c *MockError_HttpCode_Call) Run(run func()) *MockError_HttpCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockError_HttpCode_Call) Return(n int) *MockError_HttpCode_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockError_HttpCode_Call) RunAndReturn(run func() int) *MockError_HttpCode_Call {
	_c.Call.Return(run)
	return _c
}

// Message provides a mock function for the type MockError
func (_mock *MockError) Message() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Message")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockError_Message_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Message'
type MockError_Message_Call struct {
	*mock.Call
}

// Message is a helper method to define mock.On call
func (_e *MockError_Expecter) Message() *MockError_Message_Call {
	return &MockError_Message_Call{Call: _e.mock.On("Message")}
}

func (_c *MockError_Message_Call) Run(run func()) *MockError_Message_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockError_Message_Call) Return(s string) *MockError_Message_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockError_Message_Call) RunAndReturn(run func() string) *MockError_Message_Call {
	_c.Call.Return(run)
	return _c
}
