// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package client

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"golang.org/x/oauth2"
)

// NewMockOAuthClient creates a new instance of MockOAuthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOAuthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOAuthClient {
	mock := &MockOAuthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOAuthClient is an autogenerated mock type for the OAuthClient type
type MockOAuthClient struct {
	mock.Mock
}

type MockOAuthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOAuthClient) EXPECT() *MockOAuthClient_Expecter {
	return &MockOAuthClient_Expecter{mock: &_m.Mock}
}

// GetRequestMetadata provides a mock function for the type MockOAuthClient
func (_mock *MockOAuthClient) GetRequestMetadata(context1 context.Context, strings ...string) (map[string]string, error) {
	var tmpRet mock.Arguments
	if len(strings) > 0 {
		tmpRet = _mock.Called(context1, strings)
	} else {
		tmpRet = _mock.Called(context1)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetRequestMetadata")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) (map[string]string, error)); ok {
		return returnFunc(context1, strings...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) map[string]string); ok {
		r0 = returnFunc(context1, strings...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(context1, strings...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOAuthClient_GetRequestMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestMetadata'
type MockOAuthClient_GetRequestMetadata_Call struct {
	*mock.Call
}

// GetRequestMetadata is a helper method to define mock.On call
//   - context1 context.Context
//   - strings ...string
func (_e *MockOAuthClient_Expecter) GetRequestMetadata(context1 interface{}, strings ...interface{}) *MockOAuthClient_GetRequestMetadata_Call {
	return &MockOAuthClient_GetRequestMetadata_Call{Call: _e.mock.On("GetRequestMetadata",
		append([]interface{}{context1}, strings...)...)}
}

func (_c *MockOAuthClient_GetRequestMetadata_Call) Run(run func(context1 context.Context, strings ...string)) *MockOAuthClient_GetRequestMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockOAuthClient_GetRequestMetadata_Call) Return(stringToString map[string]string, err error) *MockOAuthClient_GetRequestMetadata_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockOAuthClient_GetRequestMetadata_Call) RunAndReturn(run func(context1 context.Context, strings ...string) (map[string]string, error)) *MockOAuthClient_GetRequestMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// RequireTransportSecurity provides a mock function for the type MockOAuthClient
func (_mock *MockOAuthClient) RequireTransportSecurity() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequireTransportSecurity")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockOAuthClient_RequireTransportSecurity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireTransportSecurity'
type MockOAuthClient_RequireTransportSecurity_Call struct {
	*mock.Call
}

// RequireTransportSecurity is a helper method to define mock.On call
func (_e *MockOAuthClient_Expecter) RequireTransportSecurity() *MockOAuthClient_RequireTransportSecurity_Call {
	return &MockOAuthClient_RequireTransportSecurity_Call{Call: _e.mock.On("RequireTransportSecurity")}
}

func (_c *MockOAuthClient_RequireTransportSecurity_Call) Run(run func()) *MockOAuthClient_RequireTransportSecurity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOAuthClient_RequireTransportSecurity_Call) Return(b bool) *MockOAuthClient_RequireTransportSecurity_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockOAuthClient_RequireTransportSecurity_Call) RunAndReturn(run func() bool) *MockOAuthClient_RequireTransportSecurity_Call {
	_c.Call.Return(run)
	return _c
}

// Token provides a mock function for the type MockOAuthClient
func (_mock *MockOAuthClient) Token() (*oauth2.Token, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Token")
	}

	var r0 *oauth2.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*oauth2.Token, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *oauth2.Token); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOAuthClient_Token_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Token'
type MockOAuthClient_Token_Call struct {
	*mock.Call
}

// Token is a helper method to define mock.On call
func (_e *MockOAuthClient_Expecter) Token() *MockOAuthClient_Token_Call {
	return &MockOAuthClient_Token_Call{Call: _e.mock.On("Token")}
}

func (_c *MockOAuthClient_Token_Call) Run(run func()) *MockOAuthClient_Token_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOAuthClient_Token_Call) Return(token *oauth2.Token, err error) *MockOAuthClient_Token_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockOAuthClient_Token_Call) RunAndReturn(run func() (*oauth2.Token, error)) *MockOAuthClient_Token_Call {
	_c.Call.Return(run)
	return _c
}
