// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rsa

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCipher creates a new instance of MockCipher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCipher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCipher {
	mock := &MockCipher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCipher is an autogenerated mock type for the Cipher type
type MockCipher struct {
	mock.Mock
}

type MockCipher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCipher) EXPECT() *MockCipher_Expecter {
	return &MockCipher_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type MockCipher
func (_mock *MockCipher) Decrypt(encryptedText string) (string, error) {
	ret := _mock.Called(encryptedText)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(encryptedText)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(encryptedText)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(encryptedText)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCipher_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockCipher_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - encryptedText string
func (_e *MockCipher_Expecter) Decrypt(encryptedText interface{}) *MockCipher_Decrypt_Call {
	return &MockCipher_Decrypt_Call{Call: _e.mock.On("Decrypt", encryptedText)}
}

func (_c *MockCipher_Decrypt_Call) Run(run func(encryptedText string)) *MockCipher_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCipher_Decrypt_Call) Return(s string, err error) *MockCipher_Decrypt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCipher_Decrypt_Call) RunAndReturn(run func(encryptedText string) (string, error)) *MockCipher_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type MockCipher
func (_mock *MockCipher) Encrypt(plainText string) (string, error) {
	ret := _mock.Called(plainText)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(plainText)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(plainText)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(plainText)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCipher_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockCipher_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - plainText string
func (_e *MockCipher_Expecter) Encrypt(plainText interface{}) *MockCipher_Encrypt_Call {
	return &MockCipher_Encrypt_Call{Call: _e.mock.On("Encrypt", plainText)}
}

func (_c *MockCipher_Encrypt_Call) Run(run func(plainText string)) *MockCipher_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCipher_Encrypt_Call) Return(s string, err error) *MockCipher_Encrypt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCipher_Encrypt_Call) RunAndReturn(run func(plainText string) (string, error)) *MockCipher_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Sign provides a mock function for the type MockCipher
func (_mock *MockCipher) Sign(plainText string) (string, error) {
	ret := _mock.Called(plainText)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(plainText)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(plainText)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(plainText)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCipher_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockCipher_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - plainText string
func (_e *MockCipher_Expecter) Sign(plainText interface{}) *MockCipher_Sign_Call {
	return &MockCipher_Sign_Call{Call: _e.mock.On("Sign", plainText)}
}

func (_c *MockCipher_Sign_Call) Run(run func(plainText string)) *MockCipher_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCipher_Sign_Call) Return(s string, err error) *MockCipher_Sign_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCipher_Sign_Call) RunAndReturn(run func(plainText string) (string, error)) *MockCipher_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockCipher
func (_mock *MockCipher) Verify(plainText string, signature string) error {
	ret := _mock.Called(plainText, signature)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(plainText, signature)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCipher_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockCipher_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - plainText string
//   - signature string
func (_e *MockCipher_Expecter) Verify(plainText interface{}, signature interface{}) *MockCipher_Verify_Call {
	return &MockCipher_Verify_Call{Call: _e.mock.On("Verify", plainText, signature)}
}

func (_c *MockCipher_Verify_Call) Run(run func(plainText string, signature string)) *MockCipher_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCipher_Verify_Call) Return(err error) *MockCipher_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCipher_Verify_Call) RunAndReturn(run func(plainText string, signature string) error) *MockCipher_Verify_Call {
	_c.Call.Return(run)
	return _c
}
