// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rsa

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPrivate creates a new instance of MockPrivate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrivate(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrivate {
	mock := &MockPrivate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPrivate is an autogenerated mock type for the Private type
type MockPrivate struct {
	mock.Mock
}

type MockPrivate_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrivate) EXPECT() *MockPrivate_Expecter {
	return &MockPrivate_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type MockPrivate
func (_mock *MockPrivate) Decrypt(encryptedText string) (string, error) {
	ret := _mock.Called(encryptedText)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(encryptedText)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(encryptedText)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(encryptedText)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPrivate_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockPrivate_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - encryptedText string
func (_e *MockPrivate_Expecter) Decrypt(encryptedText interface{}) *MockPrivate_Decrypt_Call {
	return &MockPrivate_Decrypt_Call{Call: _e.mock.On("Decrypt", encryptedText)}
}

func (_c *MockPrivate_Decrypt_Call) Run(run func(encryptedText string)) *MockPrivate_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPrivate_Decrypt_Call) Return(s string, err error) *MockPrivate_Decrypt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPrivate_Decrypt_Call) RunAndReturn(run func(encryptedText string) (string, error)) *MockPrivate_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Sign provides a mock function for the type MockPrivate
func (_mock *MockPrivate) Sign(plainText string) (string, error) {
	ret := _mock.Called(plainText)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(plainText)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(plainText)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(plainText)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPrivate_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockPrivate_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - plainText string
func (_e *MockPrivate_Expecter) Sign(plainText interface{}) *MockPrivate_Sign_Call {
	return &MockPrivate_Sign_Call{Call: _e.mock.On("Sign", plainText)}
}

func (_c *MockPrivate_Sign_Call) Run(run func(plainText string)) *MockPrivate_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPrivate_Sign_Call) Return(s string, err error) *MockPrivate_Sign_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPrivate_Sign_Call) RunAndReturn(run func(plainText string) (string, error)) *MockPrivate_Sign_Call {
	_c.Call.Return(run)
	return _c
}
