// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rsa

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPublic creates a new instance of MockPublic. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublic(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublic {
	mock := &MockPublic{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPublic is an autogenerated mock type for the Public type
type MockPublic struct {
	mock.Mock
}

type MockPublic_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublic) EXPECT() *MockPublic_Expecter {
	return &MockPublic_Expecter{mock: &_m.Mock}
}

// Encrypt provides a mock function for the type MockPublic
func (_mock *MockPublic) Encrypt(plainText string) (string, error) {
	ret := _mock.Called(plainText)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(plainText)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(plainText)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(plainText)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPublic_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockPublic_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - plainText string
func (_e *MockPublic_Expecter) Encrypt(plainText interface{}) *MockPublic_Encrypt_Call {
	return &MockPublic_Encrypt_Call{Call: _e.mock.On("Encrypt", plainText)}
}

func (_c *MockPublic_Encrypt_Call) Run(run func(plainText string)) *MockPublic_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPublic_Encrypt_Call) Return(s string, err error) *MockPublic_Encrypt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPublic_Encrypt_Call) RunAndReturn(run func(plainText string) (string, error)) *MockPublic_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockPublic
func (_mock *MockPublic) Verify(plainText string, signature string) error {
	ret := _mock.Called(plainText, signature)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(plainText, signature)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPublic_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockPublic_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - plainText string
//   - signature string
func (_e *MockPublic_Expecter) Verify(plainText interface{}, signature interface{}) *MockPublic_Verify_Call {
	return &MockPublic_Verify_Call{Call: _e.mock.On("Verify", plainText, signature)}
}

func (_c *MockPublic_Verify_Call) Run(run func(plainText string, signature string)) *MockPublic_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPublic_Verify_Call) Return(err error) *MockPublic_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPublic_Verify_Call) RunAndReturn(run func(plainText string, signature string) error) *MockPublic_Verify_Call {
	_c.Call.Return(run)
	return _c
}
