// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package stdlog

import (
	"github.com/pkg/errors"
	mock "github.com/stretchr/testify/mock"
)

// newMockstackTracer creates a new instance of mockstackTracer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstackTracer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstackTracer {
	mock := &mockstackTracer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstackTracer is an autogenerated mock type for the stackTracer type
type mockstackTracer struct {
	mock.Mock
}

type mockstackTracer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstackTracer) EXPECT() *mockstackTracer_Expecter {
	return &mockstackTracer_Expecter{mock: &_m.Mock}
}

// StackTrace provides a mock function for the type mockstackTracer
func (_mock *mockstackTracer) StackTrace() errors.StackTrace {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StackTrace")
	}

	var r0 errors.StackTrace
	if returnFunc, ok := ret.Get(0).(func() errors.StackTrace); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.StackTrace)
		}
	}
	return r0
}

// mockstackTracer_StackTrace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StackTrace'
type mockstackTracer_StackTrace_Call struct {
	*mock.Call
}

// StackTrace is a helper method to define mock.On call
func (_e *mockstackTracer_Expecter) StackTrace() *mockstackTracer_StackTrace_Call {
	return &mockstackTracer_StackTrace_Call{Call: _e.mock.On("StackTrace")}
}

func (_c *mockstackTracer_StackTrace_Call) Run(run func()) *mockstackTracer_StackTrace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockstackTracer_StackTrace_Call) Return(stackTrace errors.StackTrace) *mockstackTracer_StackTrace_Call {
	_c.Call.Return(stackTrace)
	return _c
}

func (_c *mockstackTracer_StackTrace_Call) RunAndReturn(run func() errors.StackTrace) *mockstackTracer_StackTrace_Call {
	_c.Call.Return(run)
	return _c
}
