// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package guid

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockGuid creates a new instance of MockGuid. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGuid(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGuid {
	mock := &MockGuid{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGuid is an autogenerated mock type for the Guid type
type MockGuid struct {
	mock.Mock
}

type MockGuid_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGuid) EXPECT() *MockGuid_Expecter {
	return &MockGuid_Expecter{mock: &_m.Mock}
}

// NewID provides a mock function for the type MockGuid
func (_mock *MockGuid) NewID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockGuid_NewID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewID'
type MockGuid_NewID_Call struct {
	*mock.Call
}

// NewID is a helper method to define mock.On call
func (_e *MockGuid_Expecter) NewID() *MockGuid_NewID_Call {
	return &MockGuid_NewID_Call{Call: _e.mock.On("NewID")}
}

func (_c *MockGuid_NewID_Call) Run(run func()) *MockGuid_NewID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGuid_NewID_Call) Return(s string) *MockGuid_NewID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockGuid_NewID_Call) RunAndReturn(run func() string) *MockGuid_NewID_Call {
	_c.Call.Return(run)
	return _c
}
