// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package hmac

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockKey creates a new instance of MockKey. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKey(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKey {
	mock := &MockKey{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKey is an autogenerated mock type for the Key type
type MockKey struct {
	mock.Mock
}

type MockKey_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKey) EXPECT() *MockKey_Expecter {
	return &MockKey_Expecter{mock: &_m.Mock}
}

// Sign provides a mock function for the type MockKey
func (_mock *MockKey) Sign(plainText string) string {
	ret := _mock.Called(plainText)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(plainText)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockKey_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockKey_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - plainText string
func (_e *MockKey_Expecter) Sign(plainText interface{}) *MockKey_Sign_Call {
	return &MockKey_Sign_Call{Call: _e.mock.On("Sign", plainText)}
}

func (_c *MockKey_Sign_Call) Run(run func(plainText string)) *MockKey_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKey_Sign_Call) Return(s string) *MockKey_Sign_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockKey_Sign_Call) RunAndReturn(run func(plainText string) string) *MockKey_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockKey
func (_mock *MockKey) Verify(plainText string, originalSignature string) error {
	ret := _mock.Called(plainText, originalSignature)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(plainText, originalSignature)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKey_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockKey_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - plainText string
//   - originalSignature string
func (_e *MockKey_Expecter) Verify(plainText interface{}, originalSignature interface{}) *MockKey_Verify_Call {
	return &MockKey_Verify_Call{Call: _e.mock.On("Verify", plainText, originalSignature)}
}

func (_c *MockKey_Verify_Call) Run(run func(plainText string, originalSignature string)) *MockKey_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKey_Verify_Call) Return(err error) *MockKey_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKey_Verify_Call) RunAndReturn(run func(plainText string, originalSignature string) error) *MockKey_Verify_Call {
	_c.Call.Return(run)
	return _c
}
